### ISSUE TITLE
Search Page

### ISSUE THREAD

**Issue by harshkumarkhatri** [shashikantdwivedi/W3schools-noAds#2] opened 2020-07-31 05:06 UTC
If we have searched about anything let us suppose HTML, then the results are shown up. if we click on any of them then they take us to the browser rather than opening the page in the app itself.

**Comment by shashikantdwivedi** [comment] 2020-07-31 17:46
Thank you for reporting the problem. The problem is fixed now

**Closed as completed by shashikantdwivedi** 2020-07-31 17:46 UTC
